"""
    Regels bij activiteiten

    <body><p>Deze API maakt het mogelijk om gegevens op te vragen, bij een applicatie die invulling geeft aan de Omgevingswetbeleidcomponent, ook wel aangeduid als plansoftware, over (Omgevingswet-)activiteiten en/of (bijbehorende) juridische regels, regelteksten en locaties.</p></body>  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: robert.melskens@vng.nl
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from openapi_client.exceptions import ApiAttributeError


def lazy_import():
    from openapi_client.model.activiteit_locatieaanduiding import ActiviteitLocatieaanduiding
    from openapi_client.model.idealisatie import Idealisatie
    from openapi_client.model.identificatie import Identificatie
    from openapi_client.model.thema import Thema
    globals()['ActiviteitLocatieaanduiding'] = ActiviteitLocatieaanduiding
    globals()['Idealisatie'] = Idealisatie
    globals()['Identificatie'] = Identificatie
    globals()['Thema'] = Thema


class JuridischeRegelVoorIedereen(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
        ('gedefinieerde_locatie_identificaties',): {
            'min_items': 1,
        },
        ('omschrijving',): {
            'min_length': 1,
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'gedefinieerde_locatie_identificaties': ([Identificatie],),  # noqa: E501
            'identificatie': (Identificatie,),  # noqa: E501
            'omschrijving': (str,),  # noqa: E501
            'regeltekst_identificatie': (Identificatie,),  # noqa: E501
            'begindatum': (date,),  # noqa: E501
            'einddatum': (date,),  # noqa: E501
            'idealisatie': (Idealisatie,),  # noqa: E501
            'normeert_activiteiten': ([ActiviteitLocatieaanduiding],),  # noqa: E501
            'themas': ([Thema],),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'gedefinieerde_locatie_identificaties': 'gedefinieerdeLocatieIdentificaties',  # noqa: E501
        'identificatie': 'identificatie',  # noqa: E501
        'omschrijving': 'omschrijving',  # noqa: E501
        'regeltekst_identificatie': 'regeltekstIdentificatie',  # noqa: E501
        'begindatum': 'begindatum',  # noqa: E501
        'einddatum': 'einddatum',  # noqa: E501
        'idealisatie': 'idealisatie',  # noqa: E501
        'normeert_activiteiten': 'normeertActiviteiten',  # noqa: E501
        'themas': 'themas',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, gedefinieerde_locatie_identificaties, identificatie, omschrijving, regeltekst_identificatie, *args, **kwargs):  # noqa: E501
        """JuridischeRegelVoorIedereen - a model defined in OpenAPI

        Args:
            gedefinieerde_locatie_identificaties ([Identificatie]): <body><p>Identificatie van de gedefinieerde locaties.</p></body>
            identificatie (Identificatie):
            omschrijving (str): <body><p>&#201;&#233;n doorlopend stuk juridische tekst zijnde een geheel of gedeelte van de tekst van een artikel of een lid.</p></body>
            regeltekst_identificatie (Identificatie):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            begindatum (date): <body><p>Datum waarop de juridischeRegelVoorIedereen relevant werd.</p></body>. [optional]  # noqa: E501
            einddatum (date): <body><p>Datum vanaf waarop de juridischeRegelVoorIedereen niet meer relevant was.</p></body>. [optional]  # noqa: E501
            idealisatie (Idealisatie): [optional]  # noqa: E501
            normeert_activiteiten ([ActiviteitLocatieaanduiding]): [optional]  # noqa: E501
            themas ([Thema]): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.gedefinieerde_locatie_identificaties = gedefinieerde_locatie_identificaties
        self.identificatie = identificatie
        self.omschrijving = omschrijving
        self.regeltekst_identificatie = regeltekst_identificatie
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, gedefinieerde_locatie_identificaties, identificatie, omschrijving, regeltekst_identificatie, *args, **kwargs):  # noqa: E501
        """JuridischeRegelVoorIedereen - a model defined in OpenAPI

        Args:
            gedefinieerde_locatie_identificaties ([Identificatie]): <body><p>Identificatie van de gedefinieerde locaties.</p></body>
            identificatie (Identificatie):
            omschrijving (str): <body><p>&#201;&#233;n doorlopend stuk juridische tekst zijnde een geheel of gedeelte van de tekst van een artikel of een lid.</p></body>
            regeltekst_identificatie (Identificatie):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            begindatum (date): <body><p>Datum waarop de juridischeRegelVoorIedereen relevant werd.</p></body>. [optional]  # noqa: E501
            einddatum (date): <body><p>Datum vanaf waarop de juridischeRegelVoorIedereen niet meer relevant was.</p></body>. [optional]  # noqa: E501
            idealisatie (Idealisatie): [optional]  # noqa: E501
            normeert_activiteiten ([ActiviteitLocatieaanduiding]): [optional]  # noqa: E501
            themas ([Thema]): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.gedefinieerde_locatie_identificaties = gedefinieerde_locatie_identificaties
        self.identificatie = identificatie
        self.omschrijving = omschrijving
        self.regeltekst_identificatie = regeltekst_identificatie
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
