/*
 * Regels bij activiteiten
 * <body><p>Deze API maakt het mogelijk om gegevens op te vragen, bij een applicatie die invulling geeft aan de Omgevingswetbeleidcomponent, ook wel aangeduid als plansoftware, over (Omgevingswet-)activiteiten en/of (bijbehorende) juridische regels, regelteksten en locaties.</p></body>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: robert.melskens@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Activiteitregelkwalificatie;

/**
 * &lt;body&gt;&lt;p&gt;Een regel voor iedereen normeert (stelt regels over) een activiteit.&lt;/p&gt;&lt;/body&gt;
 */
@ApiModel(description = "<body><p>Een regel voor iedereen normeert (stelt regels over) een activiteit.</p></body>")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-16T14:41:30.043160Z[Etc/UTC]")
public class ActiviteitLocatieaanduiding {
  public static final String SERIALIZED_NAME_ACTIVITEIT_IDENTIFICATIE = "activiteitIdentificatie";
  @SerializedName(SERIALIZED_NAME_ACTIVITEIT_IDENTIFICATIE)
  private String activiteitIdentificatie;

  public static final String SERIALIZED_NAME_ACTIVITEIT_LOCATIE_IDENTIFICATIE = "activiteitLocatieIdentificatie";
  @SerializedName(SERIALIZED_NAME_ACTIVITEIT_LOCATIE_IDENTIFICATIE)
  private String activiteitLocatieIdentificatie;

  public static final String SERIALIZED_NAME_ACTIVITEITREGELKWALIFICATIE = "activiteitregelkwalificatie";
  @SerializedName(SERIALIZED_NAME_ACTIVITEITREGELKWALIFICATIE)
  private Activiteitregelkwalificatie activiteitregelkwalificatie;

  public static final String SERIALIZED_NAME_GEKWALIFICEERDE_LOCATIE_IDENTIFICATIES = "gekwalificeerdeLocatieIdentificaties";
  @SerializedName(SERIALIZED_NAME_GEKWALIFICEERDE_LOCATIE_IDENTIFICATIES)
  private List<String> gekwalificeerdeLocatieIdentificaties = new ArrayList<>();


  public ActiviteitLocatieaanduiding activiteitIdentificatie(String activiteitIdentificatie) {
    
    this.activiteitIdentificatie = activiteitIdentificatie;
    return this;
  }

   /**
   * &lt;body&gt;&lt;p&gt;Identificatie datatype van Geonovum.&lt;/p&gt;&lt;/body&gt;
   * @return activiteitIdentificatie
  **/
  @ApiModelProperty(required = true, value = "<body><p>Identificatie datatype van Geonovum.</p></body>")

  public String getActiviteitIdentificatie() {
    return activiteitIdentificatie;
  }


  public void setActiviteitIdentificatie(String activiteitIdentificatie) {
    this.activiteitIdentificatie = activiteitIdentificatie;
  }


  public ActiviteitLocatieaanduiding activiteitLocatieIdentificatie(String activiteitLocatieIdentificatie) {
    
    this.activiteitLocatieIdentificatie = activiteitLocatieIdentificatie;
    return this;
  }

   /**
   * &lt;body&gt;&lt;p&gt;Identificatie datatype van Geonovum.&lt;/p&gt;&lt;/body&gt;
   * @return activiteitLocatieIdentificatie
  **/
  @ApiModelProperty(required = true, value = "<body><p>Identificatie datatype van Geonovum.</p></body>")

  public String getActiviteitLocatieIdentificatie() {
    return activiteitLocatieIdentificatie;
  }


  public void setActiviteitLocatieIdentificatie(String activiteitLocatieIdentificatie) {
    this.activiteitLocatieIdentificatie = activiteitLocatieIdentificatie;
  }


  public ActiviteitLocatieaanduiding activiteitregelkwalificatie(Activiteitregelkwalificatie activiteitregelkwalificatie) {
    
    this.activiteitregelkwalificatie = activiteitregelkwalificatie;
    return this;
  }

   /**
   * Get activiteitregelkwalificatie
   * @return activiteitregelkwalificatie
  **/
  @ApiModelProperty(required = true, value = "")

  public Activiteitregelkwalificatie getActiviteitregelkwalificatie() {
    return activiteitregelkwalificatie;
  }


  public void setActiviteitregelkwalificatie(Activiteitregelkwalificatie activiteitregelkwalificatie) {
    this.activiteitregelkwalificatie = activiteitregelkwalificatie;
  }


  public ActiviteitLocatieaanduiding gekwalificeerdeLocatieIdentificaties(List<String> gekwalificeerdeLocatieIdentificaties) {
    
    this.gekwalificeerdeLocatieIdentificaties = gekwalificeerdeLocatieIdentificaties;
    return this;
  }

  public ActiviteitLocatieaanduiding addGekwalificeerdeLocatieIdentificatiesItem(String gekwalificeerdeLocatieIdentificatiesItem) {
    this.gekwalificeerdeLocatieIdentificaties.add(gekwalificeerdeLocatieIdentificatiesItem);
    return this;
  }

   /**
   * &lt;body&gt;&lt;p&gt;Identificatie van de gekwalificeerde locaties.&lt;/p&gt;&lt;/body&gt;
   * @return gekwalificeerdeLocatieIdentificaties
  **/
  @ApiModelProperty(required = true, value = "<body><p>Identificatie van de gekwalificeerde locaties.</p></body>")

  public List<String> getGekwalificeerdeLocatieIdentificaties() {
    return gekwalificeerdeLocatieIdentificaties;
  }


  public void setGekwalificeerdeLocatieIdentificaties(List<String> gekwalificeerdeLocatieIdentificaties) {
    this.gekwalificeerdeLocatieIdentificaties = gekwalificeerdeLocatieIdentificaties;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActiviteitLocatieaanduiding activiteitLocatieaanduiding = (ActiviteitLocatieaanduiding) o;
    return Objects.equals(this.activiteitIdentificatie, activiteitLocatieaanduiding.activiteitIdentificatie) &&
        Objects.equals(this.activiteitLocatieIdentificatie, activiteitLocatieaanduiding.activiteitLocatieIdentificatie) &&
        Objects.equals(this.activiteitregelkwalificatie, activiteitLocatieaanduiding.activiteitregelkwalificatie) &&
        Objects.equals(this.gekwalificeerdeLocatieIdentificaties, activiteitLocatieaanduiding.gekwalificeerdeLocatieIdentificaties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activiteitIdentificatie, activiteitLocatieIdentificatie, activiteitregelkwalificatie, gekwalificeerdeLocatieIdentificaties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActiviteitLocatieaanduiding {\n");
    sb.append("    activiteitIdentificatie: ").append(toIndentedString(activiteitIdentificatie)).append("\n");
    sb.append("    activiteitLocatieIdentificatie: ").append(toIndentedString(activiteitLocatieIdentificatie)).append("\n");
    sb.append("    activiteitregelkwalificatie: ").append(toIndentedString(activiteitregelkwalificatie)).append("\n");
    sb.append("    gekwalificeerdeLocatieIdentificaties: ").append(toIndentedString(gekwalificeerdeLocatieIdentificaties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

