/*
 * Regels bij activiteiten
 * <body><p>Deze API maakt het mogelijk om gegevens op te vragen, bij een applicatie die invulling geeft aan de Omgevingswetbeleidcomponent, ook wel aangeduid als plansoftware, over (Omgevingswet-)activiteiten en/of (bijbehorende) juridische regels, regelteksten en locaties.</p></body>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: robert.melskens@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.Soortregeling;

/**
 * &lt;body&gt;&lt;p&gt;Metagegevens, conform de STOP-standaard, van het omgevingsdocument waarvan de regeltekst deel uit maakt.&lt;/p&gt;&lt;/body&gt;
 */
@ApiModel(description = "<body><p>Metagegevens, conform de STOP-standaard, van het omgevingsdocument waarvan de regeltekst deel uit maakt.</p></body>")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-16T14:41:30.043160Z[Etc/UTC]")
public class Omgevingsdocument {
  public static final String SERIALIZED_NAME_CODE_BEVOEGD_GEZAG = "codeBevoegdGezag";
  @SerializedName(SERIALIZED_NAME_CODE_BEVOEGD_GEZAG)
  private String codeBevoegdGezag;

  public static final String SERIALIZED_NAME_IDENTIFICATIE = "identificatie";
  @SerializedName(SERIALIZED_NAME_IDENTIFICATIE)
  private String identificatie;

  public static final String SERIALIZED_NAME_OPSCHRIFT = "opschrift";
  @SerializedName(SERIALIZED_NAME_OPSCHRIFT)
  private String opschrift;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private Soortregeling type;


  public Omgevingsdocument codeBevoegdGezag(String codeBevoegdGezag) {
    
    this.codeBevoegdGezag = codeBevoegdGezag;
    return this;
  }

   /**
   * &lt;body&gt;&lt;p&gt;Code van het bevoegd gezag dat de regeling vaststelt.&lt;/p&gt;&lt;/body&gt;
   * @return codeBevoegdGezag
  **/
  @ApiModelProperty(required = true, value = "<body><p>Code van het bevoegd gezag dat de regeling vaststelt.</p></body>")

  public String getCodeBevoegdGezag() {
    return codeBevoegdGezag;
  }


  public void setCodeBevoegdGezag(String codeBevoegdGezag) {
    this.codeBevoegdGezag = codeBevoegdGezag;
  }


  public Omgevingsdocument identificatie(String identificatie) {
    
    this.identificatie = identificatie;
    return this;
  }

   /**
   * &lt;body&gt;&lt;p&gt;Identificatie datatype van Geonovum.&lt;/p&gt;&lt;/body&gt;
   * @return identificatie
  **/
  @ApiModelProperty(required = true, value = "<body><p>Identificatie datatype van Geonovum.</p></body>")

  public String getIdentificatie() {
    return identificatie;
  }


  public void setIdentificatie(String identificatie) {
    this.identificatie = identificatie;
  }


  public Omgevingsdocument opschrift(String opschrift) {
    
    this.opschrift = opschrift;
    return this;
  }

   /**
   * &lt;body&gt;&lt;p&gt;De intitul&amp;#233; (offici&amp;#235;le titel) van een regeling zijnde het omgevingsdocument.&lt;/p&gt;&lt;/body&gt;
   * @return opschrift
  **/
  @ApiModelProperty(required = true, value = "<body><p>De intitul&#233; (offici&#235;le titel) van een regeling zijnde het omgevingsdocument.</p></body>")

  public String getOpschrift() {
    return opschrift;
  }


  public void setOpschrift(String opschrift) {
    this.opschrift = opschrift;
  }


  public Omgevingsdocument type(Soortregeling type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")

  public Soortregeling getType() {
    return type;
  }


  public void setType(Soortregeling type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Omgevingsdocument omgevingsdocument = (Omgevingsdocument) o;
    return Objects.equals(this.codeBevoegdGezag, omgevingsdocument.codeBevoegdGezag) &&
        Objects.equals(this.identificatie, omgevingsdocument.identificatie) &&
        Objects.equals(this.opschrift, omgevingsdocument.opschrift) &&
        Objects.equals(this.type, omgevingsdocument.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codeBevoegdGezag, identificatie, opschrift, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Omgevingsdocument {\n");
    sb.append("    codeBevoegdGezag: ").append(toIndentedString(codeBevoegdGezag)).append("\n");
    sb.append("    identificatie: ").append(toIndentedString(identificatie)).append("\n");
    sb.append("    opschrift: ").append(toIndentedString(opschrift)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

